Реализация моделей для БД
ISCRAWeb/ISCRAWebBackend pull request #10
Opened 2022-10-27 09:50 UTC by Fe-Ti

Начата работа над прототипом моделей для БД.

Что добавлено:

* Модели:
    * "Пользователь курса" с полями: роль, ссылка на глобальный аккаунт;
    * "Курс": название, описание, программа, лектор и студенты.
    * "Единица программы курса" (далее ЕПК): название/тема, описание, тип;
    * "Тип ЕПК": текстовое поле обозначающее тип (произвольный набор символов).

Последние два пункта - довольно спорное решение.

2022-10-27 09:54 UTC, Fe-Ti commented
Возникает вопрос, стоит ли делить на два поля участников курса или нет (т.е. сделать различие только по роли пользователя)?

2022-10-28 17:37 UTC, Fe-Ti commented
К предыдущему комментарию.
Есть модель курса. Можно сделать либо так:

```python
class Course(models.Model):
    name = CharField()
    description = TextField()  
    lecturer = ForeignKey(CourseUser, on_delete=models.SET_NULL)
    students = ManyToManyField(CourseUser)
    program = ManyToManyField(CourseUnit)
    materials = ManyToManyField(CourseMaterial)
```

Либо так:
```python
class Course(models.Model):
    name = CharField()
    description = TextField()  
    users = ManyToManyField(CourseUser)
    program = ManyToManyField(CourseUnit)
    materials = ManyToManyField(CourseMaterial)
```

2022-10-28 18:56 UTC, zinstack625 commented
Мне первый вариант больше нравится, так, кажется, легче представлять и нагрузка на БД будет меньше.

Насчёт нагрузки: при запросе users нужно будет фильтровать чтобы не являлся lecturer, а во втором случае будет два запроса с фильтром относительно m2m таблицы

Также сделать отдельную таблицу для CourseUser и сделать на неё отношение one2one не помешает

И наконец, всем сущностям стоит сделать булево поле available. По горькому опыту MentorWhirlpool это сильно поможет

2022-10-29 07:51 UTC, Fe-Ti commented
> Мне первый вариант больше нравится, так, кажется, легче представлять и нагрузка на БД будет меньше.

Ок, он уже в исходниках.

> Также сделать отдельную таблицу для CourseUser и сделать на неё отношение one2one не помешает

Не очень понял, где и для чего такую таблицу делать. Если это про поле "лектор", то теоретически один лектор может читать на двух курсах одновременно.

> И наконец, всем сущностям стоит сделать булево поле available. По горькому опыту MentorWhirlpool это сильно поможет

Жаль в моей сладкой жизни с этим ботом горького опыта не было. Только до сих пор висит курсач с темой "Хочу стать ментором" 😅 .

Available сделать везде? Там есть теперь модели для событий (или как мы переводим Occasions?) и новостных статей. Нужно ли делать для них тоже?

2022-10-29 11:05 UTC, zinstack625 commented
> Не очень понял, где и для чего такую таблицу делать. Если это про поле "лектор", то теоретически один лектор может читать на двух курсах одновременно.
`CourseUser.role = ForeignKey(CourseRoles, on_delete=models.SET_NULL)`, а CourseRoles пусть просто содержит строчки пока что
> Available сделать везде?
Везде, где таблица описывает сущности. M2M таблицам это делать не надо

2022-11-08 13:14 UTC, Fe-Ti commented
Подправлены недочёты в моделях (a la CharField без обязательного max_length).

Плюс начата работа над API к моделям. На данный момент реализация не закончена и поэтому не совсем рабочая.

2022-11-08 13:24 UTC, zinstack625 requested changes
Коммиты с реализацией обвязки уже давай делать в отдельном ПР. Давай отдельную ветку, которую на эту посадим, а тут оставим именно схему

2022-11-08 13:24 UTC, zinstack625 commented on iscra_web_site/main_app/models.py
> +    name = CharField(max_length=COURSE_ROLE_NAME_LEN, unique=True)  # Defines a role of a user
Мне кажется `TextField` был бы значительно более логичным. Делать ограничения на эти поля уже будем на уровне апишки

2022-11-08 13:26 UTC, zinstack625 commented
Ну или если `CharField` маппится в строку в psql - можно его оставить. Делать ограничение на количество символов - точно несуразица

2022-11-08 14:37 UTC, Fe-Ti commented
> Коммиты с реализацией обвязки уже давай делать в отдельном ПР. Давай отдельную ветку, которую на эту посадим, а тут оставим именно схему

Ок, коммит откатить или оставить?

2022-11-08 14:37 UTC, Fe-Ti commented
> Ну или если `CharField` маппится в строку в psql - можно его оставить. Делать ограничение на количество символов - точно несуразица

Согласно докам к джанго этот класс (поле) требует указывать ограничение. Поэтому переделаю под TextField.

2022-11-08 21:46 UTC, zinstack625 commented
> > Коммиты с реализацией обвязки уже давай делать в отдельном ПР. Давай отдельную ветку, которую на эту посадим, а тут оставим именно схему
> 
> Ок, коммит откатить или оставить?
> И новую ветку от master, так?

Новую ветку наверное отсюда. Коммит с реализацией функций над схемой отсюда откатить, да, но это можно потом разделить

2022-11-09 20:26 UTC, Evgenzayts commented
В курсе ещё нужно добавить поле Анонсирован/В процессе/Завершён, поле дат, в которые проводится этот курс и поле анонса (когда этот курс был анонсирован)

2022-11-09 20:31 UTC, Evgenzayts commented
CharField с ограничением количества символов наоборот выглядит логичным для name, потому что наглядно показываем, что это не то же самое, что и description, да и чтобы кто-то с дуру не сделал название в виде эссе. А зачем это нести в аптеку тем более смысла не вижу.

2022-11-15 13:42 UTC, Fe-Ti commented
> В курсе ещё нужно добавить поле Анонсирован/В процессе/Завершён
Статус уже есть в виде поля под целое число.

> поле дат, в которые проводится этот курс
> поле анонса (когда этот курс был анонсирован)

Короче, добавляем три поля DateTimeField:

* анонс,
* начало,
* конец.

> CharField с ограничением количества символов наоборот выглядит логичным для name, потому что наглядно показываем, что это не то же самое, что и description

Возникает вопрос с размером. У меня в коде закомментированы размеры, которые я прикинул исходя из текущих названий курсов.

> А зачем это нести в апишку тем более смысла не вижу.

М-м-м... Так оно в API никак по сути не отразится, только добавлением проверки на длину  (которое стоит сделать и на стороне сервера, и клиента).

2022-11-15 14:03 UTC, Fe-Ti commented
Добавлено расширение модели пользователя по умолчанию. Доступ производится из ~~последних 4-х вагонов~~ объектов модели django.contrib.auth.models.User:

```python
u = User.objects.get(<способы получить конкретного пользователя>)
print(u.additionaluserinfo.description)
```
Возможно стоит как-то иначе назвать эту модель (скажем "UserInfo").

[[Документация к этому]](https://docs.djangoproject.com/en/4.1/topics/auth/customizing/#extending-the-existing-user-model)

2022-11-15 15:40 UTC, zinstack625 commented
> Возникает вопрос с размером. У меня в коде закомментированы размеры, которые я прикинул исходя из текущих названий курсов.

Мне всё ещё не нравится идея с CharField. Принципиально - это настолько неважно, да и просто исправить, что стоит оставить так как есть

> Возможно стоит как-то иначе назвать эту модель (скажем "UserInfo").

Да, `AdditionalUserInfo` - как то длинно, а `UserInfo` - самое то

2022-11-15 15:50 UTC, zinstack625 commented
Перепроверил код, всё классно, за исключением триад полей с датами. Давай эти три поля как Женя сказал и будет аппрув

2022-11-16 23:12 UTC, zinstack625 approved these changes

2022-11-19 10:22 UTC, merged